<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
    <xsl:template match="/">
        <html xmlns="http://www.w3.org/1999/xhtml">
            <head>
            <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
                <title>Sitemap</title>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
                <meta name="robots" content="index,follow"/>
                 
              
            </head>
            <body>
            
                
                
                
                <!-- main s -->
                <div class="header"><h3>SiteMap</h3></div>
                <table class="table-container">
                    <tr class="TR">
                        <th class="">Page URL</th>
                        <th>Priority</th>
                        <th>Frequency</th>
                        <th>Last Modified</th>
                    </tr>
                    <xsl:variable name="lower" select="'abcdefghijklmnopqrstuvwxyz'"/>
                    <xsl:variable name="upper" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'"/>
                    <xsl:for-each select="./sitemap:urlset/sitemap:url">
                        <tr>
                            <xsl:if test="position() mod 2 != 1">
                                <xsl:attribute  name="class"></xsl:attribute>
                            </xsl:if>
                            <td>
                                <xsl:variable name="page">
                                    <xsl:value-of select="sitemap:loc"/>
                                </xsl:variable>
                                <a target="_blank" href="{$page}">
                                    <xsl:value-of select="sitemap:loc"/>
                                </a>
                            </td>
                            <td>
                                <xsl:value-of select="sitemap:priority"/>
                            </td>
                            <td>
                                <xsl:value-of select="sitemap:changefreq"/>
                            </td>
                            <td>
                                <xsl:value-of select="concat(substring(sitemap:lastmod, 0, 11), concat(' ', substring(sitemap:lastmod, 12, 5)))"/>
                            </td>
                        </tr>
                    </xsl:for-each>
                </table>
                <div class="footer">Generated by <a href="https://narenbairagi.in">Naren Bairagi</a> -
                    <!-- <a href="https://narenbairagi.in/">Naren bairagi</a> -->
                </div>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>